// import 'package:flutter/material.dart';
// import 'package:hexcolor/hexcolor.dart';

// import '../RAW/coloer/hex.dart';

// /* Text Clear All
//     Autogenerated by FlutLab FTF Generator
//   */
// class close_shift extends StatefulWidget {
//   @override
//   State<close_shift> createState() => _close_shiftState();
// }

// class _close_shiftState extends State<close_shift> {
//   @override
//   Widget build(BuildContext context) {
//     return 
//   }
// }
