import 'package:flutter/material.dart';

/* Rectangle Rectangle 130
    Autogenerated by FlutLab FTF Generator
  */
class layout1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 308.0,
      height: 48.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(10.0),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(10.0),
        child: Container(
          color: Color.fromARGB(255, 255, 110, 110),
        ),
      ),
    );
  }
}