import 'package:flutter/material.dart';

/* Text Order
    Autogenerated by FlutLab FTF Generator
  */
class text_order extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Order''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.2102272033691406,
        fontSize: 20.0,
        fontFamily: 'Inter',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    );
  }
}